// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIflbxnnDQMUsA1Tt9VFghBfob5nMCfMo',
    appId: '1:521968538073:web:57c3588d3e11e1f43f09c8',
    messagingSenderId: '521968538073',
    projectId: 'practice-9271a',
    authDomain: 'practice-9271a.firebaseapp.com',
    storageBucket: 'practice-9271a.appspot.com',
    measurementId: 'G-E42J55987C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZUhHZX-_XgIVCWcHI2MHrw4wNbEP2NI',
    appId: '1:521968538073:android:15bb32a0ffef3c463f09c8',
    messagingSenderId: '521968538073',
    projectId: 'practice-9271a',
    storageBucket: 'practice-9271a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGkKfKAyoEIBV_Nz2WUeXJg90uLMWjafY',
    appId: '1:521968538073:ios:1ad7263a81ce41b73f09c8',
    messagingSenderId: '521968538073',
    projectId: 'practice-9271a',
    storageBucket: 'practice-9271a.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGkKfKAyoEIBV_Nz2WUeXJg90uLMWjafY',
    appId: '1:521968538073:ios:1ad7263a81ce41b73f09c8',
    messagingSenderId: '521968538073',
    projectId: 'practice-9271a',
    storageBucket: 'practice-9271a.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIflbxnnDQMUsA1Tt9VFghBfob5nMCfMo',
    appId: '1:521968538073:web:57c3588d3e11e1f43f09c8',
    messagingSenderId: '521968538073',
    projectId: 'practice-9271a',
    authDomain: 'practice-9271a.firebaseapp.com',
    storageBucket: 'practice-9271a.appspot.com',
    measurementId: 'G-E42J55987C',
  );
}
